# Generated by Django 4.0.6 on 2022-07-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_storage_options_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='storage',
        ),
        migrations.AddField(
            model_name='organization',
            name='storage',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='inventory.storage', verbose_name='Склады'),
        ),
    ]
